// See https://aka.ms/new-console-template for more information








class InputValidateChecker
{


   
    public void checkValidate(int genarateNumber)
    {
        AutoNumberGenerator auto = new AutoNumberGenerator();

       int random = genarateNumber;
        //Console.WriteLine(genarateNumber);
        int x = 1;
        while (x > 0)
        {
            x--;
            Console.WriteLine("\t\t\t\t\t\t<< WELCOME TO DICE ROLL GAME >> \n Instructions :\nThe user enters a number from 1 to 6, which is equal to the number initially generated by the program.\n " +
                "The user enters a number that is not equal to the number initially generated by the program. (Even if the number is outside the 1-6 range, it is still a valid number, but a bad guess. One chance is lost).\n" +
                "The user enters a number that is not equal to the number initially generated by the program. \r\n" +
                "User does not enter any valid number (for example, enters “abc”).\r\n\r\n");
            Console.WriteLine("Enter Number '1st chance' :");
            int num1 = Int32.Parse(Console.ReadLine());
            if (num1 >= 0 && num1 <= 6)
            {
                if (num1 == random)
                {
                    Console.WriteLine("You Win");
                    break;
                }
                else
                {
                    Console.WriteLine("Wrong number");
                }
            }
            else
            {
                Console.WriteLine("Enter Number 0 - 6 Renge ");
            }

            Console.WriteLine("Enter Number '2nd chance' :");
            int num2 = Int32.Parse(Console.ReadLine());
            if (num2 >= 0 && num2 <= 6)
            {
                if (num2 == random)
                {
                    Console.WriteLine("You Win");
                    break;
                }
                else
                {
                    Console.WriteLine("Wrong number");
                }
            }
            else
            {
                Console.WriteLine("Enter Number 0 - 6 Renge ");
            }

            Console.WriteLine("Enter Number '3rd chance' :");
            int num3 = Int32.Parse(Console.ReadLine());

            if (num3 >= 0 && num3 <= 6)
            {
                if (num3 == random)
                {
                    Console.WriteLine("You Win");
                    break;
                }
                else
                {
                    Console.WriteLine("Wrong number");
                    Console.WriteLine("\bYou Lost\n");
                    Console.WriteLine("\t\t\t\t\tYour Winning Number : " + genarateNumber +"\n\t\t\t\t\t Welcome");
                }
            }
            else
            {
                Console.WriteLine("Enter Number 0 - 6 Renge ");
            }
        }
        
    }
}
